# Generated by Django 5.0.4 on 2024-04-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='language',
            name='abbreviation',
        ),
    ]
