# Generated by Django 5.0.4 on 2024-04-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), related_name='teachers', to='teachers.language'),
        ),
    ]
