# Generated by Django 5.0.4 on 2024-04-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='language',
            table='languages',
        ),
    ]
