# Generated by Django 5.0.4 on 2024-04-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='teachers.language'),
        ),
    ]
